### ISSUE TITLE
Imcpy Doesn't work on real Lauv vehicle

### ISSUE THREAD

**Issue by Sqaure1** [oysstu/imcpy#11] opened 2022-09-01 08:26 UTC
Hey,

Based on the follow ref example in the imcpy repo, I wrote a code that's monitor and controls a Lauv vehicle.
In the begining I worked with the dune simulator and my code works great.
Afterwards, I tried to connect to a real lauv with a manta.
First, I ensure neptus connects to the lauv and work ok.
Than, I tried to connect  to the lauv with my code.
From the lauv I received only Announce messages but from the manta I received all the messages.
I also added the lauv the my heartbeats.

When comparing the messages between me and neptus I saw some differences in some messages (at the phase before the connection to the lauv), and can relate to that if requested.

Does imcpy have been ever tested on real lauv? What can I do to make my code work?

If needed I can add my code.

Thank You.
Appreciate every help.

**Comment by oysstu** [comment] 2022-09-01 08:43
Hi, yes imcpy (old pyimc) has definitely been tested on LAUV's, but mostly running onboard the vehicle itself. The problem you are describing can be due to there being multiple network interfaces present and the networking code sending heartbeat messages on the wrong one. I've tried to make the networking more robust, but I have to be able to replicate the issues you are seeing in order to fix it.

Can you try to connect to the manta through an Ethernet cable instead of wifi, and see if that helps? In that case you should also disable the wifi network interface. Beware that the mantas has PoE outputs on some of the ports, which will fry any gigabit ethernet interface, so connect either through a PoE splitter or 100mbit switch / ethernet dongle.

You can also try to remove this line, in order to send on all available network interfaces:
https://github.com/oysstu/imcpy/blob/3ee3c90c0e2b62fe3f59628ae8000fe9365ee3bc/imcpy/node.py#L163
The reason it returns on a first possible route is to avoid duplicate messages being delivered if the node is reachable over multiple network routes

**Comment by Sqaure1** [comment] 2022-09-01 10:35
Thank you for the quick response!
I connected to the manta through an ethernet cable.
I will try what you suggested and update.

**Comment by Sqaure1** [comment] 2022-09-15 07:57
Hey,
I built the imcpy package locally with the change you suggested, on the node.py file.
Than, I connected to a real lauv, through an Ethernet cable to the manta.
Unfortunately,  the fix did not solve the problem.

Moreover, I looked at wireshark and the heartbeats & announce do arrive to the right IP (I knew the IP by comparing to Neptus wireshark).
I noticed that the source UDP port is random and changes all the time.
If lauv port is 6002.
 34243 -> 6002
34349 -> 6002
etc.
However in Neptus recordings,
If lauv port is 6002 and Neptus 6001
 6001 -> 6002
6001 -> 6002
etc

After Imcpy did not work, I tried to connect with imcjava library code and it worked well immediately.
I have decided to not use Imcpy. I hope what I wrote will help you fix the issues.

Thank You and good luck.

**Comment by oysstu** [comment] 2022-09-15 08:49
This could be related to the change in https://github.com/oysstu/imcpy/commit/bd2f4170d582f2d4fb56900e5380a35c6ce31f06, where I replaced the library for network discovery in order to simplify compilation. I'll leave this issue open until I'm able to find time to have a look at it. Thanks for providing the additional information.

**Comment by oysstu** [comment] 2022-09-15 10:36
I checked the output of the network adapter discovery mentioned above, and it is definitely picking out the right adapters on systems with many interfaces. 

Regarding the changing source port, that does not matter, as the transport is uniquely defined by the service string of the announce message. Where the messages come from should not matter, as connected systems should reply using the udp+imc service, which I believe should use a port in the 6000-6010 range. My hunch is that this is related to either multicast announce routing, heartbeat routing, og that the service string in the announce contains something odd that causes DUNE to respond at the wrong interface. 

I'm going to close this issue, as I'm unable to reproduce using lauv-simulator on different computers over either wifi and ethernet, with multiple network adapters present. The wireshark log you looked at shows that the announce and heartbeats are being sent, but not that they are received on the target system, leading me to believe that it's related to network routing.

If anyone should stumble on this issue, it would be great if they could run DUNE on the target system with the "Print Incoming Messages" enabled in Transports.Discovery to verify that announces are received. The same for the UDP transport in order to verify the heartbeats.

**Closed by oysstu** 2022-09-15 10:36 UTC
